Repository yiisoft/rbac-cycle-db, pull requests merged in 2023-03, with the labels that each got.

#34 Psalm 1 + Update StyleCI configuration
  .editorconfig
  .styleci.yml
  psalm.xml
  src/AssignmentsStorage.php
  src/ItemsStorage.php
Labels: status:code review

#47 Add workflows for other DBMS
  .github/workflows/mssql.yml
  .github/workflows/mysql.yml
  .github/workflows/pgsql.yml
  .github/workflows/sqlite.yml
  phpunit.xml.dist
  tests/Base/AssignmentsStorageTest.php
  tests/Base/Command/RbacCycleInitTest.php
  tests/Base/ItemsStorageTest.php
  tests/Base/TestCase.php
  tests/Mssql/AssignmentsStorageTest.php
  tests/Mssql/Command/RbacCycleInitTest.php
  tests/Mssql/ItemsStorageTest.php
  tests/Mssql/MssqlTrait.php
  tests/Mysql/AssignmentsStorageTest.php
  tests/Mysql/Command/RbacCycleInitTest.php
  tests/Mysql/ItemsStorageTest.php
  tests/Mysql/MysqlTrait.php
  tests/Pgsql/AssignmentsStorageTest.php
  tests/Pgsql/Command/RbacCycleInitTest.php
  tests/Pgsql/ItemsStorageTest.php
  tests/Pgsql/PgsqlTrait.php
  tests/Sqlite/AssignmentsStorageTest.php
  tests/Sqlite/Command/RbacCycleInitTest.php
  tests/Sqlite/ItemsStorageTest.php
  tests/Sqlite/SqliteTrait.php
  tests/Sqlite/runtime/.gitignore
Labels: type:test

#48 Fix errors for other DBMS and SQLite with enabled foreign keys
  CHANGELOG.md
  src/AssignmentsStorage.php
  src/Command/RbacCycleInit.php
  src/ItemsStorage.php
  tests/Base/AssignmentsStorageTest.php
  tests/Base/Command/RbacCycleInitTest.php
  tests/Base/ItemsStorageTest.php
  tests/Base/TestCase.php
  tests/Sqlite/SqliteTrait.php
Labels: type:bug
